name: Gurenge
description: "Flutter based anime watching app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  video_player: ^2.3.2
  chewie: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpeg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.jpeg"

flutter:
  uses-material-design: true